[package]
name = "winshot"
version = "0.1.0"
build = "src/main.rs"
authors = ["Peter Olds <peter@olds.co>"]

[dependencies]
winapi = "0.2.8"
user32-sys = "0.2.0"

[[bin]]
name = "winshot"
path = "src/main.rs"